### ISSUE TITLE
IllegalArgumentException: Invalid module name

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [McModLauncher/bootstraplauncher#8]
When I run `BootstrapLauncher.main(...);`, this error gets printed to the console:
```
Exception in thread "main" java.lang.IllegalArgumentException: : Invalid module name: '' is not a Java identifier
	at java.base/jdk.internal.module.Checks.requireModuleName(Checks.java:59)
	at java.base/java.lang.module.ModuleDescriptor$Builder.<init>(ModuleDescriptor.java:1515)
	at java.base/java.lang.module.ModuleDescriptor.newAutomaticModule(ModuleDescriptor.java:2395)
	at cpw.mods.jarhandling.impl.SimpleJarMetadata.descriptor(SimpleJarMetadata.java:13)
	at cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:47)
	at cpw.mods.cl.JarModuleFinder$JarModuleReference.<init>(JarModuleFinder.java:50)
	at cpw.mods.cl.JarModuleFinder.lambda$new$0(JarModuleFinder.java:28)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cpw.mods.cl.JarModuleFinder.<init>(JarModuleFinder.java:29)
	at cpw.mods.cl.JarModuleFinder.of(JarModuleFinder.java:43)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:81)
	at com.blockypenguin.barrelmc.launch.Launch.main(Launch.java:9)
```

I assumed that it was on about my code not being in a module, and when I tried fixing that, I was unable to access BootstrapLauncher due to its module-info.java not exporting anything, so I'm probably wrong there. What should I do?

**Comment by TheCurle** [comment]
I have no idea what BarrelMC is, but given it's the first thing launching when the game starts, i can only assume it's because you're developing some form of custom client.

McModLauncher is designed to only work with the base game, you're likely missing a bunch of necessary initialization.
